apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chinmayee-ingress
  namespace: chinmayee
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    appgw.ingress.kubernetes.io/health-probe-path: "/api/auth"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
  labels:
    owner: chinmayee
    project: restauranty
    created-by: chinmayee
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 3001
      - path: /api/discounts
        pathType: Prefix
        backend:
          service:
            name: discounts
            port:
              number: 3002
      - path: /api/items
        pathType: Prefix
        backend:
          service:
            name: items
            port:
              number: 3003
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
              