# File: k8s/items-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
  namespace: chinmayee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: items
        image: chinmayee606/restauranty-items:latest
        ports:
        - containerPort: 3003
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/flor"
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud-name
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud-api-key
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud-api-secret
        - name: PORT
          value: "3003"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: items
  namespace: chinmayee
spec:
  selector:
    app: items
  ports:
  - port: 3003
    targetPort: 3003