# File: k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: chinmayee
type: Opaque
data:
  # Replace these with your actual base64 values
  jwt-secret: TXlTZWNyZXQxIQ==
  cloud-name: ZGV2ZWxvcG1lbnQ=
  cloud-api-key: MTIzNDU2Nzg5
  cloud-api-secret: cGxhY2Vob2xkZXJfc2VjcmV0
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZmxvcg==
